#!/usr/bin/bash

path_to_file=$1
ip=$2
username=$3
ssh_key=$4
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
if [ $# -eq 4 ]; then
    scp "$username"@"$ip":/home/"$username" "$path"/"$path_to_file"  -i "$ssh_key" -o StrictHostKeyChecking=no
else
    echo -e "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi