#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt update -y
sudo apt install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_config_default.backup

sudo apt install haproxy -y

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s
frontend mik3-tech-frontend
    bind *:80
    default_backend mik3-tech-backend
backend mik3-tech-backend
    balance roundrobin
    server 453-web-01 35.243.128.200:80 check
    server 453-web-02 3.239.120.96:80 check
"

#echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

#echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi