#!/usr/bin/env bash
# Print "Best School" 10 times using while and print hi on 9th iteration
counter=1
while [ "$counter" -lt 11 ]
do
	echo "Best School"
	if [ "$counter" -eq 9 ]
	then
		echo "Hi"
	fi
	((counter++))
done
