#!/usr/bin/env bash
# Print "bad luck" on 4, "good luck" on 8 and "Best School" else
counter=0
while [ "$counter" -lt 10 ]
do
	if [ "$counter" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$counter" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
