#!/usr/bin/env bash
# Installing and enabling port 22, 443 and 80 port in firewall

sudo apt-get update -y

sudo apt-get install ufw -y

sudo systemctl start ufw

sudo systemctl enable ufw

sudo ufw default deny incoming

sudo ufw allow ssh

sudo ufw allow 80

sudo ufw allow 443

sudo ufw allow 22


