#!/usr/bin/env bash

# Replaces the localhost ip 127.0.0.1 with 127.0.0.2 and adds facebook ip to 8.8.8.8

cp /etc/hosts ~/hosts.new

sed -i s/^127.*$// ~/hosts.new

printf "127.0.0.2 localhost \n8.8.8.8 facebook.com" >> ~/hosts.new

cp ~/hosts.new /etc/hosts
